In [1]:
#import libraries for EDA

import pandas as pd
from matplotlib import pyplot as plot
import seaborn as sns

In [9]:
#load dataset

import os.path

datasetdir = os.path.join('.', 'dataset')
filename = 'games.csv'
path = os.path.join(datasetdir, filename)

data = pd.read_csv(path, index_col='id')

In [11]:
data['first_release_date'] = pd.to_datetime(data['first_release_date'], unit='s')
data['involved_companies'].fillna(value='1', inplace=True)
data['genres'].fillna(value='', inplace=True)
data['involved_companies'].fillna(value='', inplace=True)
data['keywords'].fillna(value='', inplace=True)
data['summary'].fillna(value='', inplace=True)

In [12]:
data

,category,rating,rating_count,aggregated_rating,first_release_date,follows,game_modes,genres,involved_companies,keywords,summary,multiplayer_modes,name,platforms,player_perspectives,similar_games,themes
id,,,,,,,,,,,,,,,,,
56115,0,NaN,NaN,NaN,1970-06-30,NaN,NaN,5,1,1 72 444 453 992 1025 1033 1208 1459 1739 2841...,"An early 3D flight simulator game, released by...",NaN,Jet Rocket,52,1,8559 10964 11171 15536 28751 57217 58075 64311...,1
11304,0,NaN,NaN,NaN,1970-09-12,NaN,1,,91161 91162,9 2396 4260,Highnoon is a BASIC game developed by Christop...,NaN,Highnoon,82 107,5,18290 58867 62473 79064 100800 103301 103302 1...,1
76506,0,NaN,NaN,NaN,1970-12-31,NaN,1,13 32,150176 150177,,"The Game of Life, also known simply as Life, i...",NaN,Game of Life,6 69 91 103,NaN,28277 33603 37419 44087 51577 65827 76263 7913...,NaN
11485,0,NaN,NaN,50.0,1971-07-01,NaN,1,5 15 30,50077,934 947 970 1025 8241,Star Trek is a text-based computer game that p...,NaN,Star Trek,104 106,5,13200 13660 17130 24620 34823 55038 57187 6828...,18
11396,0,NaN,NaN,NaN,1971-09-01,3.0,2,5,46322,947 970 1025 10211,Galaxy Game is one of the earliest known coin-...,NaN,Galaxy Game,108,3,17130 24620 55038 57187 68286 68287 78770 1032...,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148057,0,NaN,NaN,NaN,2025-05-01,NaN,1,2 9 31 32 34,135411,117 126 1416 3707 17147 24057 24401 28654 28655,Pandorex is a Point & Click Adventure featurin...,NaN,Pandorex,6,4,236 11367 18011 18841 24426 25222 26870 27725 ...,17 27 43
165549,0,NaN,NaN,NaN,2025-12-31,NaN,NaN,34,146855,,The sequel would be a direct continuation of t...,NaN,Butterfly Soup 2,6 14,5,19075 135063 137068 140022 141888 144502 14510...,27 44
214912,0,NaN,NaN,NaN,2025-12-31,NaN,1,12,185357,,Penny Blood is a alternative history horror JR...,NaN,Penny Blood,6 167 169,2,27092 54775 69007 96217 99118 106987 113636 11...,17 19 22 43
83563,0,NaN,NaN,NaN,2030-01-12,NaN,1 2,5 32,154804,466 974 3682,Enjoy the thrill of the hunt in this 6 degree ...,NaN,NeptuneGL,6,1,32902 43367 76263 96217 102868 105049 105269 1...,1
123757,0,NaN,NaN,NaN,2030-12-20,NaN,1,10 14 32,176923,,VR flight game developed for VR devices.The pl...,NaN,PilotXross,163,NaN,37419 87673 96217 106987 111130 113661 113895 ...,1